#!/bin/sh

BONUS=

for i in $@
do
	if [ "$i" = "b" ] 
	then
		BONUS="bonus"
	fi
done

make ${BONUS}

if [ $? -ne 0 ]
then
	echo -e "\033[1;31m\ncompilation error.\033[0;0m"
	python3 output_sean.py
	if [ $? -ne 0 ]
	then
		cat sean.txt
	fi
	exit 1
else
	echo "./tester $@ 2>myleaks.txt"
	./tester $@ 2>myleaks.txt
fi
